import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ".././globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <nav><ul className="flex justify-center items-center gap-1 bg-amber-50 py-5">
          <li>Home</li>
          <li>About</li>
          <li>Page</li>
          </ul></nav>
        {children}
        <footer>
          <p className="text-center text-sm text-gray-500 py-4 bg-amber-50">
            &copy; {new Date().getFullYear()} My Next.js App. All rights reserved.
          </p>
        </footer>
        </body>
    </html>
  );
}
