import { Metadata } from "next";


export const metadata: Metadata = {
  title: "Create Next blog",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  
      <body className="min-h-full flex flex-col">
        <div className="flex flex-row">
          <aside className="flex flex-col w-40 gap-2">
              <ul>
                <li>1</li>
                <li>2</li>
                <li>3</li>
              </ul>
          </aside>
          {children}
        </div>
        </body>
  );
}
